"""empty message

Revision ID: 5917f036992e
Revises: 4710f555c680
Create Date: 2023-12-08 18:49:42.267078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5917f036992e'
down_revision = '4710f555c680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('result',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sa.String(length=64),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.String(length=64),
               type_=mysql.TEXT(),
               existing_nullable=True)

    op.drop_table('users')
    # ### end Alembic commands ###
